// Seed deck: introductory mechanics. Numeric answers with g = 9.8 and a
// one percent tolerance, so 2.02 and 2.0203 both count. Every card
// redraws its numbers, which is the point: you keep the physics, not
// the arithmetic.

export const deck = {
  id: 'mech1',
  name: 'Mechanics',
  templates: [
    {
      id: 'mech1/free-fall-time',
      name: 'Time to fall',
      skills: ['free fall', 'kinematics'],
      par: 45,
      prompt: 'A rock is dropped from rest off a {{h}} m cliff. How many seconds until it lands? Take $g = 9.8\\ \\mathrm{m/s^2}$ and ignore air.',
      params: {
        h: { type: 'int', min: 10, max: 80 },
        t: { type: 'computed', expr: 'round(sqrt(2*h/9.8)*100)/100' },
      },
      answer: { type: 'number', expr: 'sqrt(2*h/9.8)', tol: 0.01, display: '{{t}}\\ \\mathrm{s}' },
      hints: ['$h = \\tfrac{1}{2} g t^2$ with nothing else going on.'],
      solution: 'From rest, $h = \\tfrac{1}{2} g t^2$, so $$t = \\sqrt{ \\frac{2h}{g} } = \\sqrt{ \\frac{2 \\cdot {{h}}}{9.8} } \\approx {{t}}\\ \\mathrm{s}$$',
    },
    {
      id: 'mech1/speed-after-accel',
      name: 'Speed after accelerating',
      skills: ['kinematics'],
      par: 30,
      prompt: 'A car moving at {{v0}} m/s accelerates at {{a}} m/s² for {{t}} s. What is its speed afterward, in m/s?',
      params: {
        v0: { type: 'int', min: 5, max: 20 },
        a: { type: 'int', min: 1, max: 4 },
        t: { type: 'int', min: 2, max: 8 },
        v: { type: 'computed', expr: 'v0 + a*t' },
      },
      answer: { type: 'number', expr: 'v0 + a*t', tol: 0.01, display: '{{v}}\\ \\mathrm{m/s}' },
      hints: ['Constant acceleration: $v = v_0 + at$.'],
      solution: '$$v = v_0 + at = {{v0}} + {{a}} \\cdot {{t}} = {{v}}\\ \\mathrm{m/s}$$',
    },
    {
      id: 'mech1/stopping-distance',
      name: 'Stopping distance',
      skills: ['kinematics'],
      par: 60,
      prompt: 'A bike moving at {{v}} m/s brakes with a steady deceleration of {{a}} m/s². How many meters does it travel before stopping?',
      params: {
        v: { type: 'int', min: 10, max: 30 },
        a: { type: 'int', min: 2, max: 8 },
        d: { type: 'computed', expr: 'round(v^2/(2*a)*100)/100' },
      },
      answer: { type: 'number', expr: 'v^2/(2*a)', tol: 0.01, display: '{{d}}\\ \\mathrm{m}' },
      hints: ['The time-free equation: $v^2 = v_0^2 + 2ad$, with the final $v$ equal to zero.'],
      solution: 'With $v_f = 0$: $$0 = v^2 - 2ad \\quad\\Rightarrow\\quad d = \\frac{v^2}{2a} = \\frac{ {{v}}^2 }{ 2 \\cdot {{a}} } \\approx {{d}}\\ \\mathrm{m}$$',
    },
    {
      id: 'mech1/range-45',
      name: 'Range at 45 degrees',
      skills: ['projectiles', 'kinematics'],
      par: 60,
      prompt: 'A ball is launched at {{v}} m/s at 45° above level ground. How far away does it land, in meters? Take $g = 9.8\\ \\mathrm{m/s^2}$.',
      params: {
        v: { type: 'int', min: 10, max: 30 },
        r: { type: 'computed', expr: 'round(v^2/9.8*100)/100' },
      },
      answer: { type: 'number', expr: 'v^2/9.8', tol: 0.01, display: '{{r}}\\ \\mathrm{m}' },
      hints: ['$R = v^2 \\sin(2\\theta)/g$, and $\\sin 90^\\circ = 1$.'],
      solution: 'The range formula $R = \\dfrac{v^2 \\sin 2\\theta}{g}$ peaks at $45^\\circ$: $$R = \\frac{ {{v}}^2 }{ 9.8 } \\approx {{r}}\\ \\mathrm{m}$$',
    },
    {
      id: 'mech1/flight-time-30',
      name: 'Time in the air',
      skills: ['projectiles', 'kinematics'],
      par: 60,
      prompt: 'A ball leaves the ground at {{v}} m/s, 30° above horizontal. How many seconds is it in the air? Take $g = 9.8\\ \\mathrm{m/s^2}$.',
      params: {
        v: { type: 'int', min: 10, max: 40 },
        t: { type: 'computed', expr: 'round(v/9.8*100)/100' },
      },
      answer: { type: 'number', expr: 'v/9.8', tol: 0.01, display: '{{t}}\\ \\mathrm{s}' },
      hints: ['Only the vertical component matters for the clock, and $\\sin 30^\\circ = \\tfrac{1}{2}$.'],
      solution: 'Vertical speed is $v \\sin 30^\\circ = v/2$, and the flight takes $2 v_y / g$: $$T = \\frac{2 \\cdot ({{v}}/2)}{9.8} = \\frac{ {{v}} }{9.8} \\approx {{t}}\\ \\mathrm{s}$$',
    },
    {
      id: 'mech1/push-with-friction',
      name: 'Pushing against friction',
      skills: ['newton\'s laws'],
      par: 75,
      prompt: 'A {{m}} kg crate is pushed along a floor with a horizontal force of {{f}} N. The kinetic friction coefficient is {{mu}}. What is the crate\'s acceleration, in m/s²? Take $g = 9.8\\ \\mathrm{m/s^2}$.',
      params: {
        m: { type: 'int', min: 2, max: 8 },
        f: { type: 'int', min: 60, max: 150 },
        mu: { type: 'float', min: 0.1, max: 0.4, dp: 1 },
        a: { type: 'computed', expr: 'round((f - mu*m*9.8)/m*100)/100' },
      },
      answer: { type: 'number', expr: '(f - mu*m*9.8)/m', tol: 0.01, display: '{{a}}\\ \\mathrm{m/s^2}' },
      hints: ['Net force first: the push minus $\\mu N$, with $N = mg$ on a flat floor.'],
      solution: '$$a = \\frac{F - \\mu m g}{m} = \\frac{ {{f}} - {{mu}} \\cdot {{m}} \\cdot 9.8 }{ {{m}} } \\approx {{a}}\\ \\mathrm{m/s^2}$$',
    },
    {
      id: 'mech1/speed-from-height',
      name: 'Speed at the bottom',
      skills: ['energy'],
      par: 45,
      prompt: 'A skateboarder starts from rest at the top of a {{h}} m ramp and rolls down without friction. How fast is she moving at the bottom, in m/s? Take $g = 9.8\\ \\mathrm{m/s^2}$.',
      params: {
        h: { type: 'int', min: 3, max: 30 },
        v: { type: 'computed', expr: 'round(sqrt(2*9.8*h)*100)/100' },
      },
      answer: { type: 'number', expr: 'sqrt(2*9.8*h)', tol: 0.01, display: '{{v}}\\ \\mathrm{m/s}' },
      hints: ['Energy, not kinematics: $mgh$ becomes $\\tfrac{1}{2} m v^2$, and the mass cancels.'],
      solution: '$$m g h = \\tfrac{1}{2} m v^2 \\quad\\Rightarrow\\quad v = \\sqrt{2 g h} = \\sqrt{2 \\cdot 9.8 \\cdot {{h}}} \\approx {{v}}\\ \\mathrm{m/s}$$',
    },
    {
      id: 'mech1/inelastic-collision',
      name: 'Sticking together',
      skills: ['momentum'],
      par: 75,
      prompt: 'A {{m1}} kg cart moving at {{v1}} m/s hits a {{m2}} kg cart moving the same way at {{v2}} m/s, and they lock together. What is their shared speed afterward, in m/s?',
      params: {
        m1: { type: 'int', min: 2, max: 6 },
        v1: { type: 'int', min: 4, max: 12 },
        m2: { type: 'int', min: 3, max: 9 },
        v2: { type: 'int', min: 0, max: 3 },
        v: { type: 'computed', expr: 'round((m1*v1 + m2*v2)/(m1+m2)*100)/100' },
      },
      answer: { type: 'number', expr: '(m1*v1 + m2*v2)/(m1+m2)', tol: 0.01, display: '{{v}}\\ \\mathrm{m/s}' },
      hints: ['Momentum is conserved; kinetic energy is not, and you do not need it.'],
      solution: '$$v = \\frac{ m_1 v_1 + m_2 v_2 }{ m_1 + m_2 } = \\frac{ {{m1}} \\cdot {{v1}} + {{m2}} \\cdot {{v2}} }{ {{m1}} + {{m2}} } \\approx {{v}}\\ \\mathrm{m/s}$$',
    },
    {
      id: 'mech1/centripetal',
      name: 'Centripetal acceleration',
      skills: ['circular motion'],
      par: 40,
      prompt: 'A car rounds a curve of radius {{r}} m at a steady {{v}} m/s. What is its acceleration, in m/s²?',
      params: {
        r: { type: 'int', min: 20, max: 120 },
        v: { type: 'int', min: 8, max: 25 },
        a: { type: 'computed', expr: 'round(v^2/r*100)/100' },
      },
      answer: { type: 'number', expr: 'v^2/r', tol: 0.01, display: '{{a}}\\ \\mathrm{m/s^2}' },
      hints: ['Steady speed does not mean zero acceleration on a curve: $a = v^2/r$, pointing at the center.'],
      solution: '$$a = \\frac{v^2}{r} = \\frac{ {{v}}^2 }{ {{r}} } \\approx {{a}}\\ \\mathrm{m/s^2}$$ toward the center of the curve.',
    },
  ],
};
